site_name: LNSS 说明文档

nav: 
  - 主页: index.md
  - 关于: about.md
  - 帮助: help.md

theme:
  name: material
  custom_dir: docs/overrides
  language: zh
  features: 
    - content.tooltips
    - content.action.edit
    - content.action.view
    - announce.dismiss
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
    - search.highlight
    - toc.follow
  palette: 
    - media: "(prefers-color-scheme)"
      toggle: 
        icon: "material/theme-light-dark"
        name: "切换至亮色主题"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: purple 
      toggle:
        icon: material/weather-sunny
        name: 切换至暗黑主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: 切换至默认主题


extra: # 额外设定
  homepage: . # 左上角徽标链接的地址（此处为一个点，也就是主页）
  social: # 联系方式（页面右下角内容）
    - icon: fontawesome/brands/github # 图标（可以去官网看有哪些）
      link: https://github.com/niuzhix/LNSS-Docs/ # 链接
      name: GitHub 仓库
    - icon: fontawesome/solid/house
      link: https://niuzhix.github.io/LNSS-Docs/
      name: 主页
    - icon: fontawesome/solid/paper-plane
      link: mailto:35690637@qq.com
      name: 联系作者
  generator: false
  extra_javascripts: 
    - extra/javascripts/typing.js
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie Consent / Cookie 许可
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
      <br/>
      我们使用 cookie 来识别您的重复访问和偏好，以及衡量我们文档的有效性和用户是否找到他们正在搜索的内容。在您的同意下，您将帮助我们改进我们的文档。
  